name: BabySteps
options:
  bundleIdPrefix: com.yu1Ro5
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.4"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
  DEVELOPMENT_TEAM: "58Y7Q3D4A7"
  CODE_SIGN_STYLE: "Automatic"
  PRODUCT_BUNDLE_IDENTIFIER: "com.yu1Ro5.BabySteps"
  # Fix code signing conflicts and ensure automatic signing works properly
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CODE_SIGN_IDENTITY[sdk=iphoneos*]: "iPhone Developer"
  CODE_SIGN_IDENTITY[sdk=iphonesimulator*]: "iPhone Developer"
  PROVISIONING_PROFILE_SPECIFIER: ""
  PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]: ""
  PROVISIONING_PROFILE_SPECIFIER[sdk=iphonesimulator*]: ""
  # Ensure automatic signing is properly configured
  CODE_SIGN_INCLUDE_ALL_CONTENT_FOR_APP: "YES"
  CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: "YES"

targets:
  BabySteps:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Sources
        type: group
    resources:
      - path: Resources
        type: group
      - path: Sources/PrivacyInfo.xcprivacy
        type: file
    settings:
      PRODUCT_NAME: "BabySteps"
      PRODUCT_BUNDLE_IDENTIFIER: "com.yu1Ro5.BabySteps"
      INFOPLIST_FILE: "Sources/Info.plist"
      GENERATE_INFOPLIST_FILE: "NO"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"
      SWIFT_EMIT_LOC_STRINGS: "YES"
      PRIVACY_MANIFEST_PATH: "Sources/PrivacyInfo.xcprivacy"
      # Ensure consistent code signing for this target
      CODE_SIGN_STYLE: "Automatic"
      CODE_SIGN_IDENTITY: "iPhone Developer"
      CODE_SIGN_IDENTITY[sdk=iphoneos*]: "iPhone Developer"
      CODE_SIGN_IDENTITY[sdk=iphonesimulator*]: "iPhone Developer"
      PROVISIONING_PROFILE_SPECIFIER: ""
      PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]: ""
      PROVISIONING_PROFILE_SPECIFIER[sdk=iphonesimulator*]: ""
      # Additional signing settings for automatic signing
      CODE_SIGN_INCLUDE_ALL_CONTENT_FOR_APP: "YES"
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: "YES"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: "BabySteps"
        CFBundleIdentifier: "com.yu1Ro5.BabySteps"
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UILaunchStoryboardName: ""
        UIMainStoryboardFile: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  BabyStepsTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Tests
        type: group
    dependencies:
      - target: BabySteps
    settings:
      PRODUCT_NAME: "BabyStepsTests"
      PRODUCT_BUNDLE_IDENTIFIER: "com.yu1Ro5.BabyStepsTests"
      INFOPLIST_FILE: "Sources/Info.plist"
      GENERATE_INFOPLIST_FILE: "NO"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/BabySteps.app/BabySteps"
      # Ensure consistent code signing for test target
      CODE_SIGN_STYLE: "Automatic"
      CODE_SIGN_IDENTITY: "iPhone Developer"
      CODE_SIGN_IDENTITY[sdk=iphoneos*]: "iPhone Developer"
      CODE_SIGN_IDENTITY[sdk=iphonesimulator*]: "iPhone Developer"
      PROVISIONING_PROFILE_SPECIFIER: ""
      PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]: ""
      PROVISIONING_PROFILE_SPECIFIER[sdk=iphonesimulator*]: ""
      # Additional signing settings for automatic signing
      CODE_SIGN_INCLUDE_ALL_CONTENT_FOR_APP: "YES"
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: "YES"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: "BabyStepsTests"
        CFBundleIdentifier: "com.yu1Ro5.BabyStepsTests"
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
