name: BabySteps
options:
  bundleIdPrefix: com.yu1Ro5
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  MARKETING_VERSION: "0.1.0"
  CURRENT_PROJECT_VERSION: "1"
  DEVELOPMENT_TEAM: "58Y7Q3D4A7"
  CODE_SIGN_STYLE: "Automatic"

targets:
  BabySteps:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources
        type: group
        excludes:
          - "Widget/**"
    resources:
      - path: Sources/Assets.xcassets
        type: folder
      - path: Sources/PrivacyInfo.xcprivacy
        type: file
    dependencies:
      - target: BabyStepsWidget
        embed: true
    settings:
      PRODUCT_NAME: "BabySteps"
      INFOPLIST_FILE: "Sources/Info.plist"
      GENERATE_INFOPLIST_FILE: "NO"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"
      SWIFT_EMIT_LOC_STRINGS: "YES"
      PRIVACY_MANIFEST_PATH: "Sources/PrivacyInfo.xcprivacy"
      CODE_SIGN_ENTITLEMENTS: "Sources/BabySteps.entitlements"

  BabyStepsWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/Widget
        type: group
      - path: Sources/Models
        type: group
    settings:
      PRODUCT_NAME: "BabyStepsWidget"
      PRODUCT_BUNDLE_IDENTIFIER: "com.yu1Ro5.BabySteps.BabyStepsWidget"
      INFOPLIST_FILE: "Sources/Widget/Info.plist"
      GENERATE_INFOPLIST_FILE: "NO"
      CODE_SIGN_ENTITLEMENTS: "Sources/Widget/BabyStepsWidget.entitlements"
      SKIP_INSTALL: "YES"

  BabyStepsTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Tests
        type: group
    dependencies:
      - target: BabySteps
    settings:
      PRODUCT_NAME: "BabyStepsTests"
      PRODUCT_BUNDLE_IDENTIFIER: "com.yu1Ro5.BabyStepsTests"
      GENERATE_INFOPLIST_FILE: "YES"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/BabySteps.app/BabySteps"
      CODE_SIGNING_ALLOWED: "NO"
      SKIP_INSTALL: "YES"
