name: BabySteps
options:
  bundleIdPrefix: com.yu1Ro5
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.4"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
  DEVELOPMENT_TEAM: "58Y7Q3D4A7"
  CODE_SIGN_STYLE: "Automatic"
  PRODUCT_BUNDLE_IDENTIFIER: "com.yu1Ro5.BabySteps"

targets:
  BabySteps:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Sources
        type: group
    resources:
      - path: Resources
        type: group
    settings:
      PRODUCT_NAME: "BabySteps"
      PRODUCT_BUNDLE_IDENTIFIER: "com.yu1Ro5.BabySteps"
      INFOPLIST_FILE: "Sources/Info.plist"
      GENERATE_INFOPLIST_FILE: "NO"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"
      SWIFT_EMIT_LOC_STRINGS: "YES"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: "BabySteps"
        CFBundleIdentifier: "com.yu1Ro5.BabySteps"
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UILaunchStoryboardName: ""
        UIMainStoryboardFile: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  BabyStepsTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Tests
        type: group
    dependencies:
      - target: BabySteps
    settings:
      PRODUCT_NAME: "BabyStepsTests"
      PRODUCT_BUNDLE_IDENTIFIER: "com.yu1Ro5.BabyStepsTests"
      GENERATE_INFOPLIST_FILE: "YES"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/BabySteps.app/BabySteps"
