name: BabySteps
options:
  bundleIdPrefix: com.yu1Ro5
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.4"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  MARKETING_VERSION: "0.0.2"
  CURRENT_PROJECT_VERSION: "1"
  DEVELOPMENT_TEAM: "58Y7Q3D4A7"
  CODE_SIGN_STYLE: "Automatic"

targets:
  BabySteps:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Sources
        type: group
    resources:
      - path: Sources/Assets.xcassets
        type: folder
      - path: Sources/PrivacyInfo.xcprivacy
        type: file
    settings:
      PRODUCT_NAME: "BabySteps"
      INFOPLIST_FILE: "Sources/Info.plist"
      GENERATE_INFOPLIST_FILE: "NO"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"
      SWIFT_EMIT_LOC_STRINGS: "YES"
      PRIVACY_MANIFEST_PATH: "Sources/PrivacyInfo.xcprivacy"

  BabyStepsTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Tests
        type: group
    dependencies:
      - target: BabySteps
    settings:
      PRODUCT_NAME: "BabyStepsTests"
      PRODUCT_BUNDLE_IDENTIFIER: "com.yu1Ro5.BabyStepsTests"
      GENERATE_INFOPLIST_FILE: "YES"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/BabySteps.app/BabySteps"
      CODE_SIGNING_ALLOWED: "NO"
      SKIP_INSTALL: "YES"

  BabyStepsUITests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Tests/BabyStepsUITests
        type: group
    dependencies:
      - target: BabySteps
    settings:
      PRODUCT_NAME: "BabyStepsUITests"
      PRODUCT_BUNDLE_IDENTIFIER: "com.yu1Ro5.BabyStepsUITests"
      GENERATE_INFOPLIST_FILE: "YES"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/BabySteps.app/BabySteps"
      TEST_TARGET_NAME: "BabySteps"
      CODE_SIGNING_ALLOWED: "NO"
      SKIP_INSTALL: "YES"
