name: BabySteps
options:
  bundleIdPrefix: com.yu1Ro5
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "14.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
  DEVELOPMENT_TEAM: "58Y7Q3D4A7"
  CODE_SIGN_STYLE: "Automatic"
  PRODUCT_BUNDLE_IDENTIFIER: "com.yu1Ro5.BabySteps"

targets:
  MyIOSApp:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources
        type: group
    resources:
      - path: Resources
        type: group
    settings:
      PRODUCT_NAME: "MyIOSApp"
      PRODUCT_BUNDLE_IDENTIFIER: "com.example.MyIOSApp"
      INFOPLIST_FILE: "Sources/Info.plist"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: "MyIOSApp"
        CFBundleIdentifier: "com.example.MyIOSApp"
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        UILaunchStoryboardName: "LaunchScreen"
        UIMainStoryboardFile: "Main"
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  MyIOSAppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Tests
        type: group
    dependencies:
      - target: MyIOSApp
    settings:
      PRODUCT_NAME: "MyIOSAppTests"
      PRODUCT_BUNDLE_IDENTIFIER: "com.example.MyIOSAppTests"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MyIOSApp.app/MyIOSApp"