name: iOS Build & TestFlight Auto

on:
  push:
    tags:
      - 'v*'  # v1.0.0, v2.1.3 などのタグで発火
  workflow_dispatch: # 手動トリガーも可能
    inputs:
      custom_version:
        description: 'Version to build (e.g., 1.0.0)'
        required: true
        type: string
        default: '1.0.0'

jobs:
  build-and-release:
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      EXPORT_OPTIONS_PLIST: ./ExportOptions.plist

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 全履歴を取得してタグを確認

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: Install XcodeGen
        run: |
          brew install xcodegen

      - name: Generate Xcode project
        run: |
          xcodegen generate
          ls -la *.xcodeproj

      - name: Get project info
        id: project_info
        run: |
          # Info.plistのパスを動的に検索
          INFO_PLIST=$(find . -name "Info.plist" -path "*/BabySteps/*" | head -1)
          if [ -z "$INFO_PLIST" ]; then
            echo "Error: Info.plist not found"
            exit 1
          fi
          
          echo "info_plist=$INFO_PLIST" >> $GITHUB_OUTPUT
          
          # タグからバージョンを抽出 (v1.2.3 -> 1.2.3)
          if [ "${{ github.event_name }}" = "push" ]; then
            TAG_VERSION="${GITHUB_REF#refs/tags/v}"
            echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT
            echo "Tag version: $TAG_VERSION"
          fi
          
          echo "Info.plist: $INFO_PLIST"

      - name: Set version and build number
        id: new_version
        run: |
          # タグからバージョンを取得、または手動入力から取得
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            NEW_VERSION="${{ github.event.inputs.custom_version }}"
          else
            TAG_VERSION="${{ steps.project_info.outputs.tag_version }}"
            NEW_VERSION="$TAG_VERSION"
          fi
          
          # ビルド番号は日時ベース
          BUILD_NUMBER=$(date +'%y%m%d%H%M')
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
          
          echo "Version: $NEW_VERSION"
          echo "Build number: $BUILD_NUMBER"

      - name: Update version and build number
        run: |
          INFO_PLIST="${{ steps.project_info.outputs.info_plist }}"
          NEW_VERSION="${{ steps.new_version.outputs.new_version }}"
          BUILD_NUMBER="${{ steps.new_version.outputs.build_number }}"
          
          echo "Updating Info.plist: $INFO_PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $NEW_VERSION" "$INFO_PLIST"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "$INFO_PLIST"
          
          echo "Version updated successfully: $NEW_VERSION ($BUILD_NUMBER)"

      - name: Build archive
        run: |
          xcodebuild -project BabySteps.xcodeproj \
                     -scheme BabySteps \
                     -configuration Release \
                     -archivePath ./build/BabySteps.xcarchive \
                     CODE_SIGN_STYLE=Automatic \
                     CODE_SIGN_IDENTITY="iPhone Distribution" \
                     CODE_SIGNING_REQUIRED=YES \
                     CODE_SIGNING_ALLOWED=YES \
                     archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath ./build/BabySteps.xcarchive \
                     -exportOptionsPlist $EXPORT_OPTIONS_PLIST \
                     -exportPath ./build
          
          ls -la ./build/

      - name: Upload to TestFlight
        run: |
          # IPAファイルの存在確認
          if [ ! -f "./build/BabySteps.ipa" ]; then
            echo "Error: IPA file not found"
            ls -la ./build/
            exit 1
          fi
          
          echo "Uploading to TestFlight..."
          xcrun altool --upload-app \
                        -f ./build/BabySteps.ipa \
                        --apiKey $APP_STORE_CONNECT_KEY_ID \
                        --apiIssuer $APP_STORE_CONNECT_ISSUER_ID \
                        --type ios

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-artifacts-v${{ steps.new_version.outputs.new_version }}
          path: build/
          retention-days: 30

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.new_version.outputs.new_version }}
          release_name: Release v${{ steps.new_version.outputs.new_version }}
          body: |
            ## What's Changed
            
            Automated release for version ${{ steps.new_version.outputs.new_version }}
            
            ### Version Info
            - **Version**: ${{ steps.new_version.outputs.new_version }}
            - **Build**: ${{ steps.new_version.outputs.build_number }}
            - **Date**: $(date -u +'%Y-%m-%d %H:%M UTC')
            
            ### Build Artifacts
            IPA file and build artifacts are available in the Actions tab.
          draft: false
          prerelease: false